### ISSUE TITLE
Help button on About tab not working

### ISSUE THREAD

**Issue by martinamorris** [nmarquezuw/fatalencounters#11]
The code here seems to have been cut and pasted from another app of ours (statnetWeb).

https://github.com/nmarquezuw/fatalencounters/blob/c5b6ef18a3a9604c3ce94b96093abd5bbbd1c7ac/inst/shiny-examples/FFSG-state/app.R#L33-L37

I'll change the text and commit, but then the button needs to be fixed so it works.

**Comment by nmarquezuw** [comment]
Issue is resolved
