### ISSUE TITLE
Include national total as a secondary axis on the raw count trends plot?

### ISSUE THREAD

**Issue by martinamorris** [nmarquezuw/fatalencounters#13]
Just read a statement that "several hundred" people are killed every year by police in the US in a [German news outlet](https://www.dw.com/en/why-german-police-officers-rarely-reach-for-their-guns/a-17884779?fbclid=IwAR3FXEHiMCfIzUrjHIw0zIXy-CL0LoX40NoEETOeTZS64fvtEofjBKzuxi4).  Several hundred are killed in CA alone.

So, I think we do need to include the counts for the National total.  The last time I looked, I couldn't find a way to do this in an R plot (!).  The secondary axis facility seems to be just a way to show a transformed y scale on the second axis.

If it's not possible, then for now let's just add a barplot for the national total to the counts page.

**Comment by nmarquezuw** [comment]
With plotly now implemented in the line plot I think its easy to show the US count total without taking away from other states especially because i have now added an option to show or hide national values. marking this as fixed.
